### PR TITLE
wallet.dat file is vulnerable if client crashes

### PR DESCRIPTION
**Pull request by fmlwlher**
wallet.dat file is vulnerable if client crashes. #29

For now each time a new block is produced the wallet.dat file is updated. However, this design is vulnerable in the case when the client crashes the private key stored in the wallet file may be lost. There are two solutions to this issue:

decouple wallet.dat from blockchain read/write.
backup wallet file each time a new block is produced.

### CODE REVIEW

**Comment by fmlwlher** [comment]
@yilugit @Clairvoyant1236

**Comment by yilugit** [comment]
+1

**Comment by yilugit** [comment]
@Clairvoyant1236 any feedback?

**Comment by Clairvoyant1236** [comment]
@yilugit Code looks good to me. I'm simulating crashes to see if the backup file stores the original wallet file correctly. Will merge it once I'm done with testing tomorrow.

**Comment by yilugit** [comment]
pay attention to the commit msg next time @fmlwlher

**Pull request merged**
